artifacts_root: artififacts

data_ingestion:
  root_dir: artififacts/data_ingestion
  source_url: https://drive.google.com/file/d/1bkHBKwieJ6P0aMpVYEbbyY9w_sstB4IF/view?usp=sharing
  local_data_file: artififacts/data_ingestion/data.zip
  unzip_dir: artififacts/data_ingestion/